// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package modelsRestApi

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonA818f49aDecode20222GoToTeamInternalServerRestAPISessionComponentDeliveryModelsRestApi(in *jlexer.Lexer, out *UserInfoBySession) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "username":
			out.Username = string(in.String())
		case "login":
			out.Login = string(in.String())
		case "avatar_img_path":
			out.AvatarImgPath = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA818f49aEncode20222GoToTeamInternalServerRestAPISessionComponentDeliveryModelsRestApi(out *jwriter.Writer, in UserInfoBySession) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"username\":"
		out.RawString(prefix[1:])
		out.String(string(in.Username))
	}
	{
		const prefix string = ",\"login\":"
		out.RawString(prefix)
		out.String(string(in.Login))
	}
	{
		const prefix string = ",\"avatar_img_path\":"
		out.RawString(prefix)
		out.String(string(in.AvatarImgPath))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UserInfoBySession) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA818f49aEncode20222GoToTeamInternalServerRestAPISessionComponentDeliveryModelsRestApi(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UserInfoBySession) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA818f49aEncode20222GoToTeamInternalServerRestAPISessionComponentDeliveryModelsRestApi(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UserInfoBySession) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA818f49aDecode20222GoToTeamInternalServerRestAPISessionComponentDeliveryModelsRestApi(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UserInfoBySession) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA818f49aDecode20222GoToTeamInternalServerRestAPISessionComponentDeliveryModelsRestApi(l, v)
}
func easyjsonA818f49aDecode20222GoToTeamInternalServerRestAPISessionComponentDeliveryModelsRestApi1(in *jlexer.Lexer, out *UserData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "email":
			out.Email = string(in.String())
		case "password":
			out.Password = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA818f49aEncode20222GoToTeamInternalServerRestAPISessionComponentDeliveryModelsRestApi1(out *jwriter.Writer, in UserData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix[1:])
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"password\":"
		out.RawString(prefix)
		out.String(string(in.Password))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UserData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA818f49aEncode20222GoToTeamInternalServerRestAPISessionComponentDeliveryModelsRestApi1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UserData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA818f49aEncode20222GoToTeamInternalServerRestAPISessionComponentDeliveryModelsRestApi1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UserData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA818f49aDecode20222GoToTeamInternalServerRestAPISessionComponentDeliveryModelsRestApi1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UserData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA818f49aDecode20222GoToTeamInternalServerRestAPISessionComponentDeliveryModelsRestApi1(l, v)
}
func easyjsonA818f49aDecode20222GoToTeamInternalServerRestAPISessionComponentDeliveryModelsRestApi2(in *jlexer.Lexer, out *SessionCreate) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "user_data":
			(out.UserData).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA818f49aEncode20222GoToTeamInternalServerRestAPISessionComponentDeliveryModelsRestApi2(out *jwriter.Writer, in SessionCreate) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"user_data\":"
		out.RawString(prefix[1:])
		(in.UserData).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SessionCreate) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA818f49aEncode20222GoToTeamInternalServerRestAPISessionComponentDeliveryModelsRestApi2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SessionCreate) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA818f49aEncode20222GoToTeamInternalServerRestAPISessionComponentDeliveryModelsRestApi2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SessionCreate) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA818f49aDecode20222GoToTeamInternalServerRestAPISessionComponentDeliveryModelsRestApi2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SessionCreate) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA818f49aDecode20222GoToTeamInternalServerRestAPISessionComponentDeliveryModelsRestApi2(l, v)
}
