serverAddress = "127.0.0.1:8081"
prometheusServerAddress = "127.0.0.1:8082"
logLevel = "debug"
logFilePath = "logs/authSessionService/logs.log"

databaseUser = "ve_ru_auth_user"
databaseName = "ve_ru"
databasePassword = "ve_ru_password"
databaseHost = "127.0.0.1"
databasePort = "5432"
databaseMaxOpenConnections = "10"