// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package modelsRestApi

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonEd4e9604Decode20222GoToTeamInternalServerRestAPICategoryComponentDeliveryModelsRestApi(in *jlexer.Lexer, out *CategoryList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "categories":
			if in.IsNull() {
				in.Skip()
				out.CategoryNames = nil
			} else {
				in.Delim('[')
				if out.CategoryNames == nil {
					if !in.IsDelim(']') {
						out.CategoryNames = make([]string, 0, 4)
					} else {
						out.CategoryNames = []string{}
					}
				} else {
					out.CategoryNames = (out.CategoryNames)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.CategoryNames = append(out.CategoryNames, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEd4e9604Encode20222GoToTeamInternalServerRestAPICategoryComponentDeliveryModelsRestApi(out *jwriter.Writer, in CategoryList) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"categories\":"
		out.RawString(prefix[1:])
		if in.CategoryNames == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.CategoryNames {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CategoryList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEd4e9604Encode20222GoToTeamInternalServerRestAPICategoryComponentDeliveryModelsRestApi(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CategoryList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEd4e9604Encode20222GoToTeamInternalServerRestAPICategoryComponentDeliveryModelsRestApi(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CategoryList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEd4e9604Decode20222GoToTeamInternalServerRestAPICategoryComponentDeliveryModelsRestApi(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CategoryList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEd4e9604Decode20222GoToTeamInternalServerRestAPICategoryComponentDeliveryModelsRestApi(l, v)
}
