// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package modelsRestApi

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonF586cbb6Decode20222GoToTeamInternalServerRestAPIUserComponentDeliveryModelsRestApi(in *jlexer.Lexer, out *UserAvatar) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "avatar_img_path":
			out.AvatarImgPath = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF586cbb6Encode20222GoToTeamInternalServerRestAPIUserComponentDeliveryModelsRestApi(out *jwriter.Writer, in UserAvatar) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"avatar_img_path\":"
		out.RawString(prefix[1:])
		out.String(string(in.AvatarImgPath))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UserAvatar) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF586cbb6Encode20222GoToTeamInternalServerRestAPIUserComponentDeliveryModelsRestApi(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UserAvatar) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF586cbb6Encode20222GoToTeamInternalServerRestAPIUserComponentDeliveryModelsRestApi(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UserAvatar) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF586cbb6Decode20222GoToTeamInternalServerRestAPIUserComponentDeliveryModelsRestApi(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UserAvatar) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF586cbb6Decode20222GoToTeamInternalServerRestAPIUserComponentDeliveryModelsRestApi(l, v)
}
