// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package createCommentary

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson285bd207Decode20222GoToTeamInternalServerRestAPICommentaryComponentDeliveryModelsRestApiCreateCommentary(in *jlexer.Lexer, out *Commentary) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "article_id":
			out.ArticleId = int(in.Int())
		case "comment_for_comment_id":
			out.CommentForCommentId = string(in.String())
		case "content":
			out.Content = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson285bd207Encode20222GoToTeamInternalServerRestAPICommentaryComponentDeliveryModelsRestApiCreateCommentary(out *jwriter.Writer, in Commentary) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"article_id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ArticleId))
	}
	{
		const prefix string = ",\"comment_for_comment_id\":"
		out.RawString(prefix)
		out.String(string(in.CommentForCommentId))
	}
	{
		const prefix string = ",\"content\":"
		out.RawString(prefix)
		out.String(string(in.Content))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Commentary) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson285bd207Encode20222GoToTeamInternalServerRestAPICommentaryComponentDeliveryModelsRestApiCreateCommentary(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Commentary) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson285bd207Encode20222GoToTeamInternalServerRestAPICommentaryComponentDeliveryModelsRestApiCreateCommentary(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Commentary) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson285bd207Decode20222GoToTeamInternalServerRestAPICommentaryComponentDeliveryModelsRestApiCreateCommentary(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Commentary) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson285bd207Decode20222GoToTeamInternalServerRestAPICommentaryComponentDeliveryModelsRestApiCreateCommentary(l, v)
}
