serverAddress = "127.0.0.1:8083"
prometheusServerAddress = "127.0.0.1:8084"
logLevel = "debug"
logFilePath = "logs/userProfileService/logs.log"

databaseUser = "postgres"
databaseName = "ve_ru"
databasePassword = "admin"
databaseHost = "127.0.0.1"
databasePort = "5432"
databaseMaxOpenConnections = "10"

authSessionServiceAddress = "127.0.0.1:8081"