# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "dev", "new_back" ]
  pull_request:
    branches: [ "dev", "new_back" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    #- name: Build
    #  run: go build -v ./...

    - name: Run go vet
      run: go vet ./...

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Run golint
      run: golint ./...
    
    - name: Build
      run: go build -o ./build/ ./...
        
    - name: Upload build result
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: ./build
      
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    #- name: Build
    #  run: go build -v ./...
      
    - name: Test
      #run: go test -race -coverpkg=./... -coverprofile=c.out `go list ./... | grep -v ".pb.go"`; go tool cover -func=c.out
      run: |
          go test -race -coverpkg=./... -coverprofile=cover.out.tmp ./...
          #cat cover.out.tmp | grep -v ./pkg/domain/grpcProtos | grep -v ./internal/authSessionService/domain | grep -v ./internal/serverRestAPI/domain | grep -v ./internal/userProfileService/domain > cover.out
          cat cover.out.tmp | grep -Ev 'pkg/domain/grpcProtos|internal/authSessionService/domain|internal/serverRestAPI/domain|internal/userProfileService/domain' > cover.out
          go tool cover -func cover.out
        
  deploy:
    #if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: ["build", "tests"]
    steps:
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: build

      - name: Transfer build files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SHH_PRIVATE_KEY }}
          source: "build/*"
          target: "/home/ubuntu/deploy_back"
          rm: true
          strip_components: 1    
      
