// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package getAllCommentariesForArticle

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD185f04bDecode20222GoToTeamInternalServerRestAPICommentaryComponentDeliveryModelsRestApiGetAllCommentariesForArticle(in *jlexer.Lexer, out *Publisher) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "username":
			out.Username = string(in.String())
		case "login":
			out.Login = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD185f04bEncode20222GoToTeamInternalServerRestAPICommentaryComponentDeliveryModelsRestApiGetAllCommentariesForArticle(out *jwriter.Writer, in Publisher) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"username\":"
		out.RawString(prefix[1:])
		out.String(string(in.Username))
	}
	{
		const prefix string = ",\"login\":"
		out.RawString(prefix)
		out.String(string(in.Login))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Publisher) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD185f04bEncode20222GoToTeamInternalServerRestAPICommentaryComponentDeliveryModelsRestApiGetAllCommentariesForArticle(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Publisher) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD185f04bEncode20222GoToTeamInternalServerRestAPICommentaryComponentDeliveryModelsRestApiGetAllCommentariesForArticle(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Publisher) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD185f04bDecode20222GoToTeamInternalServerRestAPICommentaryComponentDeliveryModelsRestApiGetAllCommentariesForArticle(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Publisher) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD185f04bDecode20222GoToTeamInternalServerRestAPICommentaryComponentDeliveryModelsRestApiGetAllCommentariesForArticle(l, v)
}
func easyjsonD185f04bDecode20222GoToTeamInternalServerRestAPICommentaryComponentDeliveryModelsRestApiGetAllCommentariesForArticle1(in *jlexer.Lexer, out *Commentary) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "comment_id":
			out.CommentId = int(in.Int())
		case "content":
			out.Content = string(in.String())
		case "rating":
			out.Rating = int(in.Int())
		case "article_id":
			out.ArticleId = int(in.Int())
		case "comment_for_comment_id":
			out.CommentForCommentId = string(in.String())
		case "publisher":
			(out.Publisher).UnmarshalEasyJSON(in)
		case "liked":
			out.Liked = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD185f04bEncode20222GoToTeamInternalServerRestAPICommentaryComponentDeliveryModelsRestApiGetAllCommentariesForArticle1(out *jwriter.Writer, in Commentary) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"comment_id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.CommentId))
	}
	{
		const prefix string = ",\"content\":"
		out.RawString(prefix)
		out.String(string(in.Content))
	}
	{
		const prefix string = ",\"rating\":"
		out.RawString(prefix)
		out.Int(int(in.Rating))
	}
	{
		const prefix string = ",\"article_id\":"
		out.RawString(prefix)
		out.Int(int(in.ArticleId))
	}
	{
		const prefix string = ",\"comment_for_comment_id\":"
		out.RawString(prefix)
		out.String(string(in.CommentForCommentId))
	}
	{
		const prefix string = ",\"publisher\":"
		out.RawString(prefix)
		(in.Publisher).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"liked\":"
		out.RawString(prefix)
		out.Int(int(in.Liked))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Commentary) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD185f04bEncode20222GoToTeamInternalServerRestAPICommentaryComponentDeliveryModelsRestApiGetAllCommentariesForArticle1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Commentary) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD185f04bEncode20222GoToTeamInternalServerRestAPICommentaryComponentDeliveryModelsRestApiGetAllCommentariesForArticle1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Commentary) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD185f04bDecode20222GoToTeamInternalServerRestAPICommentaryComponentDeliveryModelsRestApiGetAllCommentariesForArticle1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Commentary) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD185f04bDecode20222GoToTeamInternalServerRestAPICommentaryComponentDeliveryModelsRestApiGetAllCommentariesForArticle1(l, v)
}
func easyjsonD185f04bDecode20222GoToTeamInternalServerRestAPICommentaryComponentDeliveryModelsRestApiGetAllCommentariesForArticle2(in *jlexer.Lexer, out *CommentariesForArticle) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "commentaries":
			if in.IsNull() {
				in.Skip()
				out.Commentaries = nil
			} else {
				in.Delim('[')
				if out.Commentaries == nil {
					if !in.IsDelim(']') {
						out.Commentaries = make([]Commentary, 0, 0)
					} else {
						out.Commentaries = []Commentary{}
					}
				} else {
					out.Commentaries = (out.Commentaries)[:0]
				}
				for !in.IsDelim(']') {
					var v1 Commentary
					(v1).UnmarshalEasyJSON(in)
					out.Commentaries = append(out.Commentaries, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD185f04bEncode20222GoToTeamInternalServerRestAPICommentaryComponentDeliveryModelsRestApiGetAllCommentariesForArticle2(out *jwriter.Writer, in CommentariesForArticle) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"commentaries\":"
		out.RawString(prefix[1:])
		if in.Commentaries == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Commentaries {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CommentariesForArticle) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD185f04bEncode20222GoToTeamInternalServerRestAPICommentaryComponentDeliveryModelsRestApiGetAllCommentariesForArticle2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CommentariesForArticle) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD185f04bEncode20222GoToTeamInternalServerRestAPICommentaryComponentDeliveryModelsRestApiGetAllCommentariesForArticle2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CommentariesForArticle) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD185f04bDecode20222GoToTeamInternalServerRestAPICommentaryComponentDeliveryModelsRestApiGetAllCommentariesForArticle2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CommentariesForArticle) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD185f04bDecode20222GoToTeamInternalServerRestAPICommentaryComponentDeliveryModelsRestApiGetAllCommentariesForArticle2(l, v)
}
